// Generates the Fulgur visual's drive (the rcCycle keyframes) and writes it
// between the fulgur-drive markers in src/components/portfolio.module.css.
//
//   node scripts/fulgur-drive.mjs
//
// The vehicle's speed is a cruise plus a surge after each received order
// (RECEIVES, keep in sync with RC_SENDS + RC_TRAVEL in ProjectCard), braking
// to a stop at the right end of the track exactly when the stage fades out.
// It jumps a dirt mound placed where it is at TAKEOFF. Everything else in the
// visual reads --rc-t, animated by the same keyframes, so nothing can drift.
import { readFileSync, writeFileSync } from 'node:fs'

const CSS = new URL('../src/components/portfolio.module.css', import.meta.url)
const CYCLE = 8
const DT = 0.01
const RECEIVES = [0.95, 2.45, 3.95, 5.45]
const SURGES = [0.5, 2, 0.6, 0.4] // the second one launches the jump
const SURGE_TAU = 0.5
const CRUISE = 0.45
const STOP = 7.2 // the fade-out starts here (see .rcBody)
const BRAKE = 0.9
const TAKEOFF = 3.2
const MOUND = { halfWidth: 0.075, height: 9 } // x units (≈ 300px card), px
const AIR = 0.5 // flight time, s
const APEX = 18 // px above the mound top
const BOUNCE = 0.45 // landing bounce, s

const smoothstep = (e0, e1, t) => {
  const u = Math.min(1, Math.max(0, (t - e0) / (e1 - e0)))
  return u * u * (3 - 2 * u)
}
const brake = (t) => 1 - smoothstep(STOP - BRAKE, STOP, t)
const speed = (t) => {
  let v = CRUISE * smoothstep(RECEIVES[0], RECEIVES[0] + 0.55, t)
  RECEIVES.forEach((r, i) => {
    const u = (t - r) / SURGE_TAU
    if (u > 0) v += SURGES[i] * u * Math.exp(1 - u)
  })
  return v * brake(t)
}

const N = Math.round(CYCLE / DT)
const time = (i) => i * DT
const raw = [0]
for (let i = 1; i <= N; i++) raw.push(raw[i - 1] + speed(time(i)) * DT)
const scale = 1 / raw[Math.round(STOP / DT)]
const xs = raw.map((x) => Math.min(1, x * scale))
const vs = xs.map((x, i) => (x >= 1 ? 0 : speed(time(i)) * scale))
const vmax = Math.max(...vs)

// Flight : y(s) = H + a·s − b·s², peaking APEX above the mound, back to 0 at AIR.
const H = MOUND.height
const q = (2 * Math.sqrt(APEX) * AIR + Math.sqrt(4 * APEX * AIR ** 2 + 4 * AIR ** 2 * H)) / (2 * AIR ** 2)
const b = q * q
const a = 2 * Math.sqrt(APEX * b)
const moundX = xs[Math.round(TAKEOFF / DT)]
const land = TAKEOFF + AIR

const ys = []
const rs = [] // pitch, degrees, positive = nose up
for (let i = 0; i <= N; i++) {
  const s = time(i) - TAKEOFF
  let y = 0
  let r = 0
  if (s < 0 && xs[i] > moundX - MOUND.halfWidth) {
    const ph = (Math.PI * (xs[i] - moundX)) / MOUND.halfWidth
    y = (H * (1 + Math.cos(ph))) / 2
    r = 14 * Math.sin(-ph)
  } else if (s >= 0 && s < AIR) {
    y = H + a * s - b * s * s
    r = 14 - 26 * (s / AIR)
  } else if (s >= AIR && s < AIR + BOUNCE) {
    const u = (s - AIR) / BOUNCE
    y = 4 * Math.sin(Math.PI * u) * (1 - u)
    r = -12 * Math.cos(Math.PI * u * 1.5) * (1 - u)
  }
  ys.push(y)
  rs.push(r)
}

// Keyframe stops : position and speed every 0.1s, height and pitch every
// 0.04s around the jump. A property missing from a stop is interpolated
// between the stops that set it.
const stops = new Map()
const put = (i, prop, value) => {
  if (!stops.has(i)) stops.set(i, {})
  stops.get(i)[prop] = value
}
const fmt = (n, digits) => {
  const s = n.toFixed(digits).replace(/\.?0+$/, '')
  return s === '-0' ? '0' : s
}
for (let i = 0; i <= N; i += 10) {
  put(i, '--rc-x', fmt(xs[i], 4))
  put(i, '--rc-s', fmt(vs[i] / vmax, 3))
}
const airborne = ys.map((y, i) => (y || rs[i] ? i : -1)).filter((i) => i >= 0)
const [first, last] = [airborne[0] - 4, airborne.at(-1) + 4]
for (let i = Math.max(0, first - (first % 4)); i <= Math.min(N, last); i += 4) {
  put(i, '--rc-y', fmt(ys[i], 2))
  put(i, '--rc-r', fmt(rs[i], 2))
}
for (const i of [0, N]) {
  put(i, '--rc-t', String(time(i)))
  put(i, '--rc-y', '0')
  put(i, '--rc-r', '0')
}

const body = [...stops.keys()]
  .sort((m, n) => m - n)
  .map((i) => {
    const decls = Object.entries(stops.get(i))
      .map(([prop, value]) => `${prop}: ${value};`)
      .join(' ')
    return `  ${fmt((i / N) * 100, 2)}% { ${decls} }`
  })
  .join('\n')

const block = `/* fulgur-drive:start — generated by scripts/fulgur-drive.mjs, do not edit. */
.rc {
  --rc-mound: ${fmt(moundX, 4)};
  --rc-land: ${fmt(xs[Math.round(land / DT)], 4)};
  --rc-land-t: ${fmt(land, 2)};
}
@keyframes rcCycle {
${body}
}
/* fulgur-drive:end */`

const css = readFileSync(CSS, 'utf8')
const markers = /\/\* fulgur-drive:start[\s\S]*?\/\* fulgur-drive:end \*\//
if (!markers.test(css)) throw new Error('fulgur-drive markers not found in portfolio.module.css')
writeFileSync(CSS, css.replace(markers, block))
console.log(`mound at x ${fmt(moundX, 3)}, lands at x ${fmt(xs[Math.round(land / DT)], 3)} (${fmt(land, 2)}s), ${stops.size} stops`)
